#! /usr/bin/env node
var Hook = require('../lib/hookio').Hook;

var battle = new Hook({ 
  name: "battle"
});

battle.listen({
  port: 5000,
  host: "localhost"
});

console.log('Barracks has started!'.green);
console.log('Waiting for soliders...'.yellow);

/*
// Connect a single hook to current hook
battle.spawn('gunner');

// Connect multiple hooks to current hook
battle.spawn(['sfx', 'scout', 'ammo_guy']);

// Connect current hook to another hook
battle.connect({
  port: 5001,
  host: "localhost"
});
*/

battle.on('out', function(name, data){
  console.log('Barracks is emitting output ', name, data);
});

battle.on('in', function(event, event2, data){
  console.log('generic input :', event, event2, data);
  //console.log(cliff.inspect(data));
});

battle.on('in.*', function(event, event2, data){
  //console.log(event.yellow, cliff.inspect(data));
});