#! /usr/bin/env node
var Hook    = require('../lib/hookio').Hook;

var battle = new Hook({ 
  name: "battle"
});

battle.listen();

console.log('The battle has started!'.green);
console.log('Waiting for actors to connect...'.yellow);

/*

// Connect a single hook to current hook
battle.spawn('gunner');

// Connect multiple hooks to current hook
battle.spawn(['sfx', 'scout', 'ammo_guy', 'enemy']);

// Connect current hook to another hook
battle.connect({
  port: 5001,
  host: "localhost"
});
*/

battle.on('out', function(name, data){
  console.log('Barracks is emitting output ', name, data);
});

battle.on('in', function(event, event2, data){
  console.log('generic input :', event, event2, data);
  //console.log(cliff.inspect(data));
});

battle.on('in.*', function(event, event2, data){
  console.log(event.yellow, event2, JSON.stringify(data));
});