#! /usr/bin/env node
var Hook = require('../lib/hookio').Hook;

var scout = new Hook({name: 'scout'});

scout.connect({
  port: 5000,
  host: "localhost"
});

scout.on('ready', function(){

  scout.on('in.enemy.appears', function(event, enemy) {
    // Add a 3 second delay to simulate I/O for the scout
    // NOTE: This setTimeout is for simulating I/O, don't use setTimeout
    setTimeout(function(){
      console.log('Enemy has been sighted!'.yellow);
      scout.emit("out.spottedEnemy", enemy );
    }, 800);
  });

  scout.on('in.enemy.hit', function(event, enemy) {
    console.log('Enemy has been hit!'.yellow);
  });

  scout.on('in.enemy.disappear', function(event, enemy) {
    console.log('Enemy has disappeared!'.yellow);
  });
  
});